// Code generated by ent, DO NOT EDIT.

package ent

import (
	"step/internal/data/ent/award"
	"step/internal/data/ent/schema"
	"step/internal/data/ent/show"
	"step/internal/data/ent/showreserve"
	"step/internal/data/ent/step"
	"step/internal/data/ent/target"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	awardFields := schema.Award{}.Fields()
	_ = awardFields
	// awardDescSettedAt is the schema descriptor for setted_at field.
	awardDescSettedAt := awardFields[10].Descriptor()
	// award.DefaultSettedAt holds the default value on creation for the setted_at field.
	award.DefaultSettedAt = awardDescSettedAt.Default.(int64)
	showFields := schema.Show{}.Fields()
	_ = showFields
	// showDescCreatedAt is the schema descriptor for created_at field.
	showDescCreatedAt := showFields[5].Descriptor()
	// show.DefaultCreatedAt holds the default value on creation for the created_at field.
	show.DefaultCreatedAt = showDescCreatedAt.Default.(int64)
	showreserveFields := schema.ShowReserve{}.Fields()
	_ = showreserveFields
	// showreserveDescCreatedAt is the schema descriptor for created_at field.
	showreserveDescCreatedAt := showreserveFields[4].Descriptor()
	// showreserve.DefaultCreatedAt holds the default value on creation for the created_at field.
	showreserve.DefaultCreatedAt = showreserveDescCreatedAt.Default.(int64)
	stepFields := schema.Step{}.Fields()
	_ = stepFields
	// stepDescTitle is the schema descriptor for title field.
	stepDescTitle := stepFields[1].Descriptor()
	// step.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	step.TitleValidator = stepDescTitle.Validators[0].(func(string) error)
	// stepDescDescription is the schema descriptor for description field.
	stepDescDescription := stepFields[2].Descriptor()
	// step.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	step.DescriptionValidator = stepDescDescription.Validators[0].(func(string) error)
	// stepDescIsChallenge is the schema descriptor for is_challenge field.
	stepDescIsChallenge := stepFields[3].Descriptor()
	// step.DefaultIsChallenge holds the default value on creation for the is_challenge field.
	step.DefaultIsChallenge = stepDescIsChallenge.Default.(bool)
	// stepDescCreatedAt is the schema descriptor for created_at field.
	stepDescCreatedAt := stepFields[9].Descriptor()
	// step.DefaultCreatedAt holds the default value on creation for the created_at field.
	step.DefaultCreatedAt = stepDescCreatedAt.Default.(int64)
	targetFields := schema.Target{}.Fields()
	_ = targetFields
	// targetDescTitle is the schema descriptor for title field.
	targetDescTitle := targetFields[2].Descriptor()
	// target.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	target.TitleValidator = targetDescTitle.Validators[0].(func(string) error)
	// targetDescDescription is the schema descriptor for description field.
	targetDescDescription := targetFields[3].Descriptor()
	// target.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	target.DescriptionValidator = targetDescDescription.Validators[0].(func(string) error)
	// targetDescType is the schema descriptor for type field.
	targetDescType := targetFields[4].Descriptor()
	// target.DefaultType holds the default value on creation for the type field.
	target.DefaultType = targetDescType.Default.(string)
	// targetDescCreatedAt is the schema descriptor for created_at field.
	targetDescCreatedAt := targetFields[5].Descriptor()
	// target.DefaultCreatedAt holds the default value on creation for the created_at field.
	target.DefaultCreatedAt = targetDescCreatedAt.Default.(int64)
	// targetDescLayer is the schema descriptor for layer field.
	targetDescLayer := targetFields[9].Descriptor()
	// target.DefaultLayer holds the default value on creation for the layer field.
	target.DefaultLayer = targetDescLayer.Default.(uint32)
}
