// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"step/internal/data/ent/predicate"
	"step/internal/data/ent/show"
	"step/internal/data/ent/showreserve"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShowQuery is the builder for querying Show entities.
type ShowQuery struct {
	config
	ctx              *QueryContext
	order            []show.OrderOption
	inters           []Interceptor
	predicates       []predicate.Show
	withShowReserves *ShowReserveQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShowQuery builder.
func (sq *ShowQuery) Where(ps ...predicate.Show) *ShowQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *ShowQuery) Limit(limit int) *ShowQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *ShowQuery) Offset(offset int) *ShowQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *ShowQuery) Unique(unique bool) *ShowQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *ShowQuery) Order(o ...show.OrderOption) *ShowQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryShowReserves chains the current query on the "show_reserves" edge.
func (sq *ShowQuery) QueryShowReserves() *ShowReserveQuery {
	query := (&ShowReserveClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(show.Table, show.FieldID, selector),
			sqlgraph.To(showreserve.Table, showreserve.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, show.ShowReservesTable, show.ShowReservesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Show entity from the query.
// Returns a *NotFoundError when no Show was found.
func (sq *ShowQuery) First(ctx context.Context) (*Show, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{show.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *ShowQuery) FirstX(ctx context.Context) *Show {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Show ID from the query.
// Returns a *NotFoundError when no Show ID was found.
func (sq *ShowQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{show.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *ShowQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Show entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Show entity is found.
// Returns a *NotFoundError when no Show entities are found.
func (sq *ShowQuery) Only(ctx context.Context) (*Show, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{show.Label}
	default:
		return nil, &NotSingularError{show.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *ShowQuery) OnlyX(ctx context.Context) *Show {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Show ID in the query.
// Returns a *NotSingularError when more than one Show ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *ShowQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{show.Label}
	default:
		err = &NotSingularError{show.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *ShowQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Shows.
func (sq *ShowQuery) All(ctx context.Context) ([]*Show, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Show, *ShowQuery]()
	return withInterceptors[[]*Show](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *ShowQuery) AllX(ctx context.Context) []*Show {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Show IDs.
func (sq *ShowQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(show.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *ShowQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *ShowQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*ShowQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *ShowQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *ShowQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *ShowQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShowQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *ShowQuery) Clone() *ShowQuery {
	if sq == nil {
		return nil
	}
	return &ShowQuery{
		config:           sq.config,
		ctx:              sq.ctx.Clone(),
		order:            append([]show.OrderOption{}, sq.order...),
		inters:           append([]Interceptor{}, sq.inters...),
		predicates:       append([]predicate.Show{}, sq.predicates...),
		withShowReserves: sq.withShowReserves.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithShowReserves tells the query-builder to eager-load the nodes that are connected to
// the "show_reserves" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *ShowQuery) WithShowReserves(opts ...func(*ShowReserveQuery)) *ShowQuery {
	query := (&ShowReserveClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withShowReserves = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Show.Query().
//		GroupBy(show.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *ShowQuery) GroupBy(field string, fields ...string) *ShowGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShowGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = show.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.Show.Query().
//		Select(show.FieldType).
//		Scan(ctx, &v)
func (sq *ShowQuery) Select(fields ...string) *ShowSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &ShowSelect{ShowQuery: sq}
	sbuild.label = show.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShowSelect configured with the given aggregations.
func (sq *ShowQuery) Aggregate(fns ...AggregateFunc) *ShowSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *ShowQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !show.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *ShowQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Show, error) {
	var (
		nodes       = []*Show{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withShowReserves != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Show).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Show{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withShowReserves; query != nil {
		if err := sq.loadShowReserves(ctx, query, nodes,
			func(n *Show) { n.Edges.ShowReserves = []*ShowReserve{} },
			func(n *Show, e *ShowReserve) { n.Edges.ShowReserves = append(n.Edges.ShowReserves, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *ShowQuery) loadShowReserves(ctx context.Context, query *ShowReserveQuery, nodes []*Show, init func(*Show), assign func(*Show, *ShowReserve)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Show)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(showreserve.FieldRefShowID)
	}
	query.Where(predicate.ShowReserve(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(show.ShowReservesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RefShowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ref_show_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *ShowQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *ShowQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(show.Table, show.Columns, sqlgraph.NewFieldSpec(show.FieldID, field.TypeUint64))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, show.FieldID)
		for i := range fields {
			if fields[i] != show.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *ShowQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(show.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = show.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range sq.modifiers {
		m(selector)
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sq *ShowQuery) Modify(modifiers ...func(s *sql.Selector)) *ShowSelect {
	sq.modifiers = append(sq.modifiers, modifiers...)
	return sq.Select()
}

// ShowGroupBy is the group-by builder for Show entities.
type ShowGroupBy struct {
	selector
	build *ShowQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *ShowGroupBy) Aggregate(fns ...AggregateFunc) *ShowGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *ShowGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShowQuery, *ShowGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *ShowGroupBy) sqlScan(ctx context.Context, root *ShowQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShowSelect is the builder for selecting fields of Show entities.
type ShowSelect struct {
	*ShowQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *ShowSelect) Aggregate(fns ...AggregateFunc) *ShowSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *ShowSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShowQuery, *ShowSelect](ctx, ss.ShowQuery, ss, ss.inters, v)
}

func (ss *ShowSelect) sqlScan(ctx context.Context, root *ShowQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ss *ShowSelect) Modify(modifiers ...func(s *sql.Selector)) *ShowSelect {
	ss.modifiers = append(ss.modifiers, modifiers...)
	return ss
}
