// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"step/internal/data/ent/predicate"
	"step/internal/data/ent/show"
	"step/internal/data/ent/showreserve"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShowReserveQuery is the builder for querying ShowReserve entities.
type ShowReserveQuery struct {
	config
	ctx        *QueryContext
	order      []showreserve.OrderOption
	inters     []Interceptor
	predicates []predicate.ShowReserve
	withShow   *ShowQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShowReserveQuery builder.
func (srq *ShowReserveQuery) Where(ps ...predicate.ShowReserve) *ShowReserveQuery {
	srq.predicates = append(srq.predicates, ps...)
	return srq
}

// Limit the number of records to be returned by this query.
func (srq *ShowReserveQuery) Limit(limit int) *ShowReserveQuery {
	srq.ctx.Limit = &limit
	return srq
}

// Offset to start from.
func (srq *ShowReserveQuery) Offset(offset int) *ShowReserveQuery {
	srq.ctx.Offset = &offset
	return srq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srq *ShowReserveQuery) Unique(unique bool) *ShowReserveQuery {
	srq.ctx.Unique = &unique
	return srq
}

// Order specifies how the records should be ordered.
func (srq *ShowReserveQuery) Order(o ...showreserve.OrderOption) *ShowReserveQuery {
	srq.order = append(srq.order, o...)
	return srq
}

// QueryShow chains the current query on the "show" edge.
func (srq *ShowReserveQuery) QueryShow() *ShowQuery {
	query := (&ShowClient{config: srq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(showreserve.Table, showreserve.FieldID, selector),
			sqlgraph.To(show.Table, show.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, showreserve.ShowTable, showreserve.ShowColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ShowReserve entity from the query.
// Returns a *NotFoundError when no ShowReserve was found.
func (srq *ShowReserveQuery) First(ctx context.Context) (*ShowReserve, error) {
	nodes, err := srq.Limit(1).All(setContextOp(ctx, srq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{showreserve.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srq *ShowReserveQuery) FirstX(ctx context.Context) *ShowReserve {
	node, err := srq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ShowReserve ID from the query.
// Returns a *NotFoundError when no ShowReserve ID was found.
func (srq *ShowReserveQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(1).IDs(setContextOp(ctx, srq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{showreserve.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srq *ShowReserveQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := srq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ShowReserve entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ShowReserve entity is found.
// Returns a *NotFoundError when no ShowReserve entities are found.
func (srq *ShowReserveQuery) Only(ctx context.Context) (*ShowReserve, error) {
	nodes, err := srq.Limit(2).All(setContextOp(ctx, srq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{showreserve.Label}
	default:
		return nil, &NotSingularError{showreserve.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srq *ShowReserveQuery) OnlyX(ctx context.Context) *ShowReserve {
	node, err := srq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ShowReserve ID in the query.
// Returns a *NotSingularError when more than one ShowReserve ID is found.
// Returns a *NotFoundError when no entities are found.
func (srq *ShowReserveQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(2).IDs(setContextOp(ctx, srq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{showreserve.Label}
	default:
		err = &NotSingularError{showreserve.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srq *ShowReserveQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := srq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ShowReserves.
func (srq *ShowReserveQuery) All(ctx context.Context) ([]*ShowReserve, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryAll)
	if err := srq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ShowReserve, *ShowReserveQuery]()
	return withInterceptors[[]*ShowReserve](ctx, srq, qr, srq.inters)
}

// AllX is like All, but panics if an error occurs.
func (srq *ShowReserveQuery) AllX(ctx context.Context) []*ShowReserve {
	nodes, err := srq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ShowReserve IDs.
func (srq *ShowReserveQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if srq.ctx.Unique == nil && srq.path != nil {
		srq.Unique(true)
	}
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryIDs)
	if err = srq.Select(showreserve.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srq *ShowReserveQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := srq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srq *ShowReserveQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryCount)
	if err := srq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, srq, querierCount[*ShowReserveQuery](), srq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (srq *ShowReserveQuery) CountX(ctx context.Context) int {
	count, err := srq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srq *ShowReserveQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryExist)
	switch _, err := srq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (srq *ShowReserveQuery) ExistX(ctx context.Context) bool {
	exist, err := srq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShowReserveQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srq *ShowReserveQuery) Clone() *ShowReserveQuery {
	if srq == nil {
		return nil
	}
	return &ShowReserveQuery{
		config:     srq.config,
		ctx:        srq.ctx.Clone(),
		order:      append([]showreserve.OrderOption{}, srq.order...),
		inters:     append([]Interceptor{}, srq.inters...),
		predicates: append([]predicate.ShowReserve{}, srq.predicates...),
		withShow:   srq.withShow.Clone(),
		// clone intermediate query.
		sql:  srq.sql.Clone(),
		path: srq.path,
	}
}

// WithShow tells the query-builder to eager-load the nodes that are connected to
// the "show" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *ShowReserveQuery) WithShow(opts ...func(*ShowQuery)) *ShowReserveQuery {
	query := (&ShowClient{config: srq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	srq.withShow = query
	return srq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ShowReserve.Query().
//		GroupBy(showreserve.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (srq *ShowReserveQuery) GroupBy(field string, fields ...string) *ShowReserveGroupBy {
	srq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShowReserveGroupBy{build: srq}
	grbuild.flds = &srq.ctx.Fields
	grbuild.label = showreserve.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.ShowReserve.Query().
//		Select(showreserve.FieldUserID).
//		Scan(ctx, &v)
func (srq *ShowReserveQuery) Select(fields ...string) *ShowReserveSelect {
	srq.ctx.Fields = append(srq.ctx.Fields, fields...)
	sbuild := &ShowReserveSelect{ShowReserveQuery: srq}
	sbuild.label = showreserve.Label
	sbuild.flds, sbuild.scan = &srq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShowReserveSelect configured with the given aggregations.
func (srq *ShowReserveQuery) Aggregate(fns ...AggregateFunc) *ShowReserveSelect {
	return srq.Select().Aggregate(fns...)
}

func (srq *ShowReserveQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range srq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, srq); err != nil {
				return err
			}
		}
	}
	for _, f := range srq.ctx.Fields {
		if !showreserve.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srq.path != nil {
		prev, err := srq.path(ctx)
		if err != nil {
			return err
		}
		srq.sql = prev
	}
	return nil
}

func (srq *ShowReserveQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ShowReserve, error) {
	var (
		nodes       = []*ShowReserve{}
		_spec       = srq.querySpec()
		loadedTypes = [1]bool{
			srq.withShow != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ShowReserve).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ShowReserve{config: srq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(srq.modifiers) > 0 {
		_spec.Modifiers = srq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, srq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := srq.withShow; query != nil {
		if err := srq.loadShow(ctx, query, nodes, nil,
			func(n *ShowReserve, e *Show) { n.Edges.Show = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (srq *ShowReserveQuery) loadShow(ctx context.Context, query *ShowQuery, nodes []*ShowReserve, init func(*ShowReserve), assign func(*ShowReserve, *Show)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*ShowReserve)
	for i := range nodes {
		fk := nodes[i].RefShowID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(show.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ref_show_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (srq *ShowReserveQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srq.querySpec()
	if len(srq.modifiers) > 0 {
		_spec.Modifiers = srq.modifiers
	}
	_spec.Node.Columns = srq.ctx.Fields
	if len(srq.ctx.Fields) > 0 {
		_spec.Unique = srq.ctx.Unique != nil && *srq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, srq.driver, _spec)
}

func (srq *ShowReserveQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(showreserve.Table, showreserve.Columns, sqlgraph.NewFieldSpec(showreserve.FieldID, field.TypeUint64))
	_spec.From = srq.sql
	if unique := srq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if srq.path != nil {
		_spec.Unique = true
	}
	if fields := srq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, showreserve.FieldID)
		for i := range fields {
			if fields[i] != showreserve.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if srq.withShow != nil {
			_spec.Node.AddColumnOnce(showreserve.FieldRefShowID)
		}
	}
	if ps := srq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srq *ShowReserveQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srq.driver.Dialect())
	t1 := builder.Table(showreserve.Table)
	columns := srq.ctx.Fields
	if len(columns) == 0 {
		columns = showreserve.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srq.sql != nil {
		selector = srq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if srq.ctx.Unique != nil && *srq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range srq.modifiers {
		m(selector)
	}
	for _, p := range srq.predicates {
		p(selector)
	}
	for _, p := range srq.order {
		p(selector)
	}
	if offset := srq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (srq *ShowReserveQuery) Modify(modifiers ...func(s *sql.Selector)) *ShowReserveSelect {
	srq.modifiers = append(srq.modifiers, modifiers...)
	return srq.Select()
}

// ShowReserveGroupBy is the group-by builder for ShowReserve entities.
type ShowReserveGroupBy struct {
	selector
	build *ShowReserveQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srgb *ShowReserveGroupBy) Aggregate(fns ...AggregateFunc) *ShowReserveGroupBy {
	srgb.fns = append(srgb.fns, fns...)
	return srgb
}

// Scan applies the selector query and scans the result into the given value.
func (srgb *ShowReserveGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srgb.build.ctx, ent.OpQueryGroupBy)
	if err := srgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShowReserveQuery, *ShowReserveGroupBy](ctx, srgb.build, srgb, srgb.build.inters, v)
}

func (srgb *ShowReserveGroupBy) sqlScan(ctx context.Context, root *ShowReserveQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(srgb.fns))
	for _, fn := range srgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*srgb.flds)+len(srgb.fns))
		for _, f := range *srgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*srgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShowReserveSelect is the builder for selecting fields of ShowReserve entities.
type ShowReserveSelect struct {
	*ShowReserveQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (srs *ShowReserveSelect) Aggregate(fns ...AggregateFunc) *ShowReserveSelect {
	srs.fns = append(srs.fns, fns...)
	return srs
}

// Scan applies the selector query and scans the result into the given value.
func (srs *ShowReserveSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srs.ctx, ent.OpQuerySelect)
	if err := srs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShowReserveQuery, *ShowReserveSelect](ctx, srs.ShowReserveQuery, srs, srs.inters, v)
}

func (srs *ShowReserveSelect) sqlScan(ctx context.Context, root *ShowReserveQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(srs.fns))
	for _, fn := range srs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*srs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (srs *ShowReserveSelect) Modify(modifiers ...func(s *sql.Selector)) *ShowReserveSelect {
	srs.modifiers = append(srs.modifiers, modifiers...)
	return srs
}
