// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"step/internal/data/ent/predicate"
	"step/internal/data/ent/steprate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StepRateQuery is the builder for querying StepRate entities.
type StepRateQuery struct {
	config
	ctx        *QueryContext
	order      []steprate.OrderOption
	inters     []Interceptor
	predicates []predicate.StepRate
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StepRateQuery builder.
func (srq *StepRateQuery) Where(ps ...predicate.StepRate) *StepRateQuery {
	srq.predicates = append(srq.predicates, ps...)
	return srq
}

// Limit the number of records to be returned by this query.
func (srq *StepRateQuery) Limit(limit int) *StepRateQuery {
	srq.ctx.Limit = &limit
	return srq
}

// Offset to start from.
func (srq *StepRateQuery) Offset(offset int) *StepRateQuery {
	srq.ctx.Offset = &offset
	return srq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srq *StepRateQuery) Unique(unique bool) *StepRateQuery {
	srq.ctx.Unique = &unique
	return srq
}

// Order specifies how the records should be ordered.
func (srq *StepRateQuery) Order(o ...steprate.OrderOption) *StepRateQuery {
	srq.order = append(srq.order, o...)
	return srq
}

// First returns the first StepRate entity from the query.
// Returns a *NotFoundError when no StepRate was found.
func (srq *StepRateQuery) First(ctx context.Context) (*StepRate, error) {
	nodes, err := srq.Limit(1).All(setContextOp(ctx, srq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{steprate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srq *StepRateQuery) FirstX(ctx context.Context) *StepRate {
	node, err := srq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StepRate ID from the query.
// Returns a *NotFoundError when no StepRate ID was found.
func (srq *StepRateQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(1).IDs(setContextOp(ctx, srq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{steprate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srq *StepRateQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := srq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StepRate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StepRate entity is found.
// Returns a *NotFoundError when no StepRate entities are found.
func (srq *StepRateQuery) Only(ctx context.Context) (*StepRate, error) {
	nodes, err := srq.Limit(2).All(setContextOp(ctx, srq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{steprate.Label}
	default:
		return nil, &NotSingularError{steprate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srq *StepRateQuery) OnlyX(ctx context.Context) *StepRate {
	node, err := srq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StepRate ID in the query.
// Returns a *NotSingularError when more than one StepRate ID is found.
// Returns a *NotFoundError when no entities are found.
func (srq *StepRateQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(2).IDs(setContextOp(ctx, srq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{steprate.Label}
	default:
		err = &NotSingularError{steprate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srq *StepRateQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := srq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StepRates.
func (srq *StepRateQuery) All(ctx context.Context) ([]*StepRate, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryAll)
	if err := srq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StepRate, *StepRateQuery]()
	return withInterceptors[[]*StepRate](ctx, srq, qr, srq.inters)
}

// AllX is like All, but panics if an error occurs.
func (srq *StepRateQuery) AllX(ctx context.Context) []*StepRate {
	nodes, err := srq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StepRate IDs.
func (srq *StepRateQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if srq.ctx.Unique == nil && srq.path != nil {
		srq.Unique(true)
	}
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryIDs)
	if err = srq.Select(steprate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srq *StepRateQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := srq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srq *StepRateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryCount)
	if err := srq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, srq, querierCount[*StepRateQuery](), srq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (srq *StepRateQuery) CountX(ctx context.Context) int {
	count, err := srq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srq *StepRateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryExist)
	switch _, err := srq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (srq *StepRateQuery) ExistX(ctx context.Context) bool {
	exist, err := srq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StepRateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srq *StepRateQuery) Clone() *StepRateQuery {
	if srq == nil {
		return nil
	}
	return &StepRateQuery{
		config:     srq.config,
		ctx:        srq.ctx.Clone(),
		order:      append([]steprate.OrderOption{}, srq.order...),
		inters:     append([]Interceptor{}, srq.inters...),
		predicates: append([]predicate.StepRate{}, srq.predicates...),
		// clone intermediate query.
		sql:  srq.sql.Clone(),
		path: srq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StepRate.Query().
//		GroupBy(steprate.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (srq *StepRateQuery) GroupBy(field string, fields ...string) *StepRateGroupBy {
	srq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StepRateGroupBy{build: srq}
	grbuild.flds = &srq.ctx.Fields
	grbuild.label = steprate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.StepRate.Query().
//		Select(steprate.FieldUserID).
//		Scan(ctx, &v)
func (srq *StepRateQuery) Select(fields ...string) *StepRateSelect {
	srq.ctx.Fields = append(srq.ctx.Fields, fields...)
	sbuild := &StepRateSelect{StepRateQuery: srq}
	sbuild.label = steprate.Label
	sbuild.flds, sbuild.scan = &srq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StepRateSelect configured with the given aggregations.
func (srq *StepRateQuery) Aggregate(fns ...AggregateFunc) *StepRateSelect {
	return srq.Select().Aggregate(fns...)
}

func (srq *StepRateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range srq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, srq); err != nil {
				return err
			}
		}
	}
	for _, f := range srq.ctx.Fields {
		if !steprate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srq.path != nil {
		prev, err := srq.path(ctx)
		if err != nil {
			return err
		}
		srq.sql = prev
	}
	return nil
}

func (srq *StepRateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StepRate, error) {
	var (
		nodes = []*StepRate{}
		_spec = srq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StepRate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StepRate{config: srq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(srq.modifiers) > 0 {
		_spec.Modifiers = srq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, srq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (srq *StepRateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srq.querySpec()
	if len(srq.modifiers) > 0 {
		_spec.Modifiers = srq.modifiers
	}
	_spec.Node.Columns = srq.ctx.Fields
	if len(srq.ctx.Fields) > 0 {
		_spec.Unique = srq.ctx.Unique != nil && *srq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, srq.driver, _spec)
}

func (srq *StepRateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(steprate.Table, steprate.Columns, sqlgraph.NewFieldSpec(steprate.FieldID, field.TypeUint64))
	_spec.From = srq.sql
	if unique := srq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if srq.path != nil {
		_spec.Unique = true
	}
	if fields := srq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, steprate.FieldID)
		for i := range fields {
			if fields[i] != steprate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := srq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srq *StepRateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srq.driver.Dialect())
	t1 := builder.Table(steprate.Table)
	columns := srq.ctx.Fields
	if len(columns) == 0 {
		columns = steprate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srq.sql != nil {
		selector = srq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if srq.ctx.Unique != nil && *srq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range srq.modifiers {
		m(selector)
	}
	for _, p := range srq.predicates {
		p(selector)
	}
	for _, p := range srq.order {
		p(selector)
	}
	if offset := srq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (srq *StepRateQuery) Modify(modifiers ...func(s *sql.Selector)) *StepRateSelect {
	srq.modifiers = append(srq.modifiers, modifiers...)
	return srq.Select()
}

// StepRateGroupBy is the group-by builder for StepRate entities.
type StepRateGroupBy struct {
	selector
	build *StepRateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srgb *StepRateGroupBy) Aggregate(fns ...AggregateFunc) *StepRateGroupBy {
	srgb.fns = append(srgb.fns, fns...)
	return srgb
}

// Scan applies the selector query and scans the result into the given value.
func (srgb *StepRateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srgb.build.ctx, ent.OpQueryGroupBy)
	if err := srgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StepRateQuery, *StepRateGroupBy](ctx, srgb.build, srgb, srgb.build.inters, v)
}

func (srgb *StepRateGroupBy) sqlScan(ctx context.Context, root *StepRateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(srgb.fns))
	for _, fn := range srgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*srgb.flds)+len(srgb.fns))
		for _, f := range *srgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*srgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StepRateSelect is the builder for selecting fields of StepRate entities.
type StepRateSelect struct {
	*StepRateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (srs *StepRateSelect) Aggregate(fns ...AggregateFunc) *StepRateSelect {
	srs.fns = append(srs.fns, fns...)
	return srs
}

// Scan applies the selector query and scans the result into the given value.
func (srs *StepRateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srs.ctx, ent.OpQuerySelect)
	if err := srs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StepRateQuery, *StepRateSelect](ctx, srs.StepRateQuery, srs, srs.inters, v)
}

func (srs *StepRateSelect) sqlScan(ctx context.Context, root *StepRateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(srs.fns))
	for _, fn := range srs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*srs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (srs *StepRateSelect) Modify(modifiers ...func(s *sql.Selector)) *StepRateSelect {
	srs.modifiers = append(srs.modifiers, modifiers...)
	return srs
}
