// Code generated by ent, DO NOT EDIT.

package show

import (
	"step/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Show {
	return predicate.Show(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Show {
	return predicate.Show(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Show {
	return predicate.Show(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Show {
	return predicate.Show(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Show {
	return predicate.Show(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Show {
	return predicate.Show(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Show {
	return predicate.Show(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldType, v))
}

// Poster applies equality check predicate on the "poster" field. It's identical to PosterEQ.
func Poster(v string) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldPoster, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldCreatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Show {
	return predicate.Show(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Show {
	return predicate.Show(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Show {
	return predicate.Show(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Show {
	return predicate.Show(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Show {
	return predicate.Show(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Show {
	return predicate.Show(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Show {
	return predicate.Show(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Show {
	return predicate.Show(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Show {
	return predicate.Show(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Show {
	return predicate.Show(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Show {
	return predicate.Show(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Show {
	return predicate.Show(sql.FieldContainsFold(FieldType, v))
}

// PosterEQ applies the EQ predicate on the "poster" field.
func PosterEQ(v string) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldPoster, v))
}

// PosterNEQ applies the NEQ predicate on the "poster" field.
func PosterNEQ(v string) predicate.Show {
	return predicate.Show(sql.FieldNEQ(FieldPoster, v))
}

// PosterIn applies the In predicate on the "poster" field.
func PosterIn(vs ...string) predicate.Show {
	return predicate.Show(sql.FieldIn(FieldPoster, vs...))
}

// PosterNotIn applies the NotIn predicate on the "poster" field.
func PosterNotIn(vs ...string) predicate.Show {
	return predicate.Show(sql.FieldNotIn(FieldPoster, vs...))
}

// PosterGT applies the GT predicate on the "poster" field.
func PosterGT(v string) predicate.Show {
	return predicate.Show(sql.FieldGT(FieldPoster, v))
}

// PosterGTE applies the GTE predicate on the "poster" field.
func PosterGTE(v string) predicate.Show {
	return predicate.Show(sql.FieldGTE(FieldPoster, v))
}

// PosterLT applies the LT predicate on the "poster" field.
func PosterLT(v string) predicate.Show {
	return predicate.Show(sql.FieldLT(FieldPoster, v))
}

// PosterLTE applies the LTE predicate on the "poster" field.
func PosterLTE(v string) predicate.Show {
	return predicate.Show(sql.FieldLTE(FieldPoster, v))
}

// PosterContains applies the Contains predicate on the "poster" field.
func PosterContains(v string) predicate.Show {
	return predicate.Show(sql.FieldContains(FieldPoster, v))
}

// PosterHasPrefix applies the HasPrefix predicate on the "poster" field.
func PosterHasPrefix(v string) predicate.Show {
	return predicate.Show(sql.FieldHasPrefix(FieldPoster, v))
}

// PosterHasSuffix applies the HasSuffix predicate on the "poster" field.
func PosterHasSuffix(v string) predicate.Show {
	return predicate.Show(sql.FieldHasSuffix(FieldPoster, v))
}

// PosterIsNil applies the IsNil predicate on the "poster" field.
func PosterIsNil() predicate.Show {
	return predicate.Show(sql.FieldIsNull(FieldPoster))
}

// PosterNotNil applies the NotNil predicate on the "poster" field.
func PosterNotNil() predicate.Show {
	return predicate.Show(sql.FieldNotNull(FieldPoster))
}

// PosterEqualFold applies the EqualFold predicate on the "poster" field.
func PosterEqualFold(v string) predicate.Show {
	return predicate.Show(sql.FieldEqualFold(FieldPoster, v))
}

// PosterContainsFold applies the ContainsFold predicate on the "poster" field.
func PosterContainsFold(v string) predicate.Show {
	return predicate.Show(sql.FieldContainsFold(FieldPoster, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Show {
	return predicate.Show(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Show {
	return predicate.Show(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Show {
	return predicate.Show(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Show {
	return predicate.Show(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Show {
	return predicate.Show(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Show {
	return predicate.Show(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Show {
	return predicate.Show(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Show {
	return predicate.Show(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Show {
	return predicate.Show(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Show {
	return predicate.Show(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Show {
	return predicate.Show(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Show {
	return predicate.Show(sql.FieldContainsFold(FieldContent, v))
}

// MediaFilesIsNil applies the IsNil predicate on the "media_files" field.
func MediaFilesIsNil() predicate.Show {
	return predicate.Show(sql.FieldIsNull(FieldMediaFiles))
}

// MediaFilesNotNil applies the NotNil predicate on the "media_files" field.
func MediaFilesNotNil() predicate.Show {
	return predicate.Show(sql.FieldNotNull(FieldMediaFiles))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Show {
	return predicate.Show(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Show {
	return predicate.Show(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Show {
	return predicate.Show(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Show {
	return predicate.Show(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Show {
	return predicate.Show(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Show {
	return predicate.Show(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Show {
	return predicate.Show(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Show {
	return predicate.Show(sql.FieldLTE(FieldCreatedAt, v))
}

// HasShowReserves applies the HasEdge predicate on the "show_reserves" edge.
func HasShowReserves() predicate.Show {
	return predicate.Show(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ShowReservesTable, ShowReservesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShowReservesWith applies the HasEdge predicate on the "show_reserves" edge with a given conditions (other predicates).
func HasShowReservesWith(preds ...predicate.ShowReserve) predicate.Show {
	return predicate.Show(func(s *sql.Selector) {
		step := newShowReservesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Show) predicate.Show {
	return predicate.Show(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Show) predicate.Show {
	return predicate.Show(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Show) predicate.Show {
	return predicate.Show(sql.NotPredicates(p))
}
